---
- name: Clone lotus git repository
  become: true
  become_user: "{{ lotus_user }}"
  when: install_type == "source"
  git:
    force: true
    repo: "{{ git_url }}"
    dest: "{{ install_dir }}"
    version: "{{ git_version }}"
    recursive: yes
    update: yes
  tags:
    - install
    - source

- name: Make clean source
  become: true
  become_user: "{{ lotus_user }}"
  when: install_type == "source"
  make:
    chdir: "{{ install_dir }}"
    target: clean
  environment:
    PATH: "{{ cargo_home }}/bin:{{ ansible_env.PATH }}"
    CARGO_HOME: "{{ cargo_home }}"
  changed_when: false
  tags:
    - install
    - source

- debug:
    var: cargo_home

- name: Make target
  become: true
  become_user: "{{ lotus_user }}"
  when: install_type == "source"
  make:
    chdir: "{{ install_dir }}"
    target: "{{ lotus_make_target }}"
  environment:
    PATH: "{{ cargo_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: false
  tags:
    - install
    - source

- name: Install lotus client and miner software
  become: true
  when: install_type == "source"
  make:
    chdir: "{{ install_dir }}"
    target: "{{ lotus_make_install_target }}"
  environment:
    PATH: "{{ cargo_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: false
  tags:
    - install
    - source

- name: Ensure proper permissions of install directory post build
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    recurse: true
  changed_when: false
  tags:
    - install
    - source


