---
- name: Setup Lotus systemd unit
  include_role:
    name: altlabs.systemd
  vars:
    perform_uninstall: perform_uninstall
    unit_config:
      - name: lotus
        Unit:
          Description: Lotus
          Documentation: https://docs.lotu.sh/
          Wants: network-online.target
          After: network-online.target
        Service: "{{ _default_service_unit | combine(custom_unit_properties) }}"
        Install:
          WantedBy: multi-user.target
  tags:
    - launch

- name: Ensure start of lotus daemon service
  become: true
  when: not perform_uninstall|bool
  service:
    name: lotus
    state: started
    enabled: "yes"
  tags:
    - launch
